### ISSUE TITLE
Add a LICENCE  

### ISSUE THREAD

**Issue by dharmeshkakadia** [intel-hadoop/PAT#11]
We have been using some of this tooling and want to continue (and contribute) :) It would be useful to add a LICENCE to clarify.

**Comment by agruza** [comment]
Thank you for the feedback. Will look into it.

--Agata

**Comment by agruza** [comment]
PAT uses 3-clause BSD License. At the beginning of each file you should be able to see full license text. Is there something specific about this License that you would like to know?

**Comment by dharmeshkakadia** [comment]
Thanks @agruza. May be we should add LICENSE file at the root of the repo explicitly to make  it clearer?

**Comment by agruza** [comment]
Great idea. I have just added LICENSE file at the root of the repo. Please keep good idea coming :)
