### ISSUE TITLE
PAT failes if /usr/bin/awk does not link to gawk

### ISSUE THREAD

**Issue by Michael-Frank** [intel-hadoop/PAT#3]
Not every linux distribution comes with gawk as the default awk link, but gawk is required because of "strftime" used in e.g.  PAT/WORKER_scripts/instruments.
If gawk is not the default awk, pat will silently fail and not produce any results.

On debian 7 only  /usr/bin/nawk and /usr/bin/mawk are installed.

Please place a hint in readme.md pointing out this issue/requirement for gawk or make the awk binary path a configurable parameter in config.

best regards
Michael

**Comment by asonje** [comment]
Thanks Michael,

I apologize for the delay. I have edited the README and will consider
adding a configurable awk path.

Thanks
