### ISSUE TITLE
Result dir may be deleted because of the wrong settings.

### ISSUE THREAD

**Issue by wakamori** [intel-hadoop/PAT#4]
When the following conditions are met at the same time, the result directory is deleted.

* `WORKER_SCRIPT_DIR` and `MASTER_SCRIPT_DIR` is the same value.
* `ALL_NODES` includes the master node (the master node is also a worker node).

I think the above situation is likely to occur because the default INSTRUCTIONS in README.txt suggests `ALL_NODES` can include the master node, and the default values of `WORKER_SCRIPT_DIR` and `MASTER_SCRIPT_DIR` are the same.

To avoid this, we propose following corrections. (just examples)

* Add the notes in README.txt to avoid
* Modify the default values of `WORKER_SCRIPT_DIR` and `MASTER_SCRIPT_DIR`
* Modify the runall script to work correct.

Regards,

**Comment by asonje** [comment]
just addressed the issue in the latest commit. give it a try.

**Comment by wakamori** [comment]
It works fine, thanks!
